name: Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ui && npm install --global vercel@latest
      - run: cd ui && vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: cd ui && vercel build --token=${{ secrets.VERCEL_TOKEN }} --prod
      - run: cd ui && vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
